name: Check HTML

on:
  pull_request:
    paths:
      - '**.html'

jobs:
  html-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install HTMLHint
        run: |
          npm install -g htmlhint

      - name: Run HTMLHint
        run: |
          htmlhint "**/*.html"
